### ISSUE TITLE
Feedback for Screen designer

### ISSUE THREAD

**Issue by giedresuperoffice** [SuperOfficeDocs/superoffice-docs#1257]
Hi, 
it seems like you need to have not just Field administrator, but General administrator functional right to access Screen designer. If you have just Field administrator, you see the button, but when you click on it, it does not load and the icon is bouncing - showing that it's loading but nothing is loaded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.superOffice.com ➟ Docs Team processing.*

* Content Source: [help-en-screen-designer](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/en/ui/screen-designer/learn/index.md/#L1)

**Comment by digitaldiina** [comment]
@giedresuperoffice what you experienced with the Screen Designer turned out to be a bug. You need the functional right Field administrator **or** General administrator.

We normally don't specify 'General administrator' as an alternative since full access is implied - do you think it is necessary in this case?

**Comment by digitaldiina** [comment]
I'm closing this issue now since it was a product bug. Please reach out again if you have more feedback, @giedresuperoffice :)
