### ISSUE TITLE
Help: Admin - Screen designer - Update info about publish entities

### ISSUE THREAD

**Issue by kirstiaa** [SuperOfficeDocs/superoffice-docs#432]
Need to update the file with info about the need to publish/restore each entity.
So publish/restore on Company, will not publish/restore on the other entities.

Karl Martin Andersen 08.09.2022 09:45 • 
Mårn Kirsti 🙂
Jeg har litt input for Admin hjelpefila (Fields - Edit fields), ref:
https://help.superoffice.com/Documentation/Help/EN/CRM/10.1/WebHelpAdmin/index.htm#t=fields_web%2FEditing_fields_web.htm&rhsearch=publish

Jeg/vi visste faktisk ikke at når man publiserer felt i Admin - Fields (udef) så publiserer man bare på entiteten man står på. Dvs. har man lagt til nytt felt på Company og på Sale så må man publisere en-for-en (Company, Sale osv)
Dette er jo utelukkende positivt men vi visste det hvertfall ikke.
I min case veldig kjekt da kunden hadde slettet noen felt på Company samt endret mange felt på Sale og Document. Og de ville i utgangspunktet bare få frem de slettede feltene igjen. Noe som denne gangen var mulig da de ikke hadde publisert 🙂

**Comment by thaugholt** [comment]
OK. Added the following to the last step in editing-fields.md:
"The changes will only be published for the current entity (current tab). Example: If you have made changes in several tabs without publishing, you will have to click Publish in each tab to publish the changes."
Changes pushed to github. Also fixed in RoboHelp.
