### ISSUE TITLE
Merge Online Application Development and Developer Portal documentation

### ISSUE THREAD

**Issue by SuperOfficeDevNet** [SuperOfficeDocs/superoffice-docs#490]
Audience: tech, dev

Area: Online application development
 
Title: Merge Online Application Development and Developer Portal documentation

Description: Merge the online application documentation with the developer portal documentation.

https://docs.superoffice.com/apps/index.html
https://docs.superoffice.com/developer-portal/index.html

Organize these in such a way that consumers/readers easily/organically understand how to create/work with online applications, tenants, validations, certifications, etc.

### Other changes

* For App Store, installed apps - add info about this page and "Report a problem".
* Add a note about production sandbox and link to *online/sandbox/clone-to.md*.
* Consider moving *authentication/online/which-flow-to-use.md* to DP folder.

**Comment by digitaldiina** [comment]
### Links between the two sections

*developer-portal* links to *apps* 76 times in 21 files
*apps* links to *developer-portal* 27 times in 16 files

### Incoming links

Other pages links to *DP* 13 times in 9 files and to *apps* 67 times in 41 files

Many of these are in index pages and go to terminology, tutorial, or getting access to SOD/DP.

**Comment by digitaldiina** [comment]
### New top folder name

While there are more links to *apps*, I think *developer-portal* is a more descriptive name. After introducing DP, we've gradually moved or deleted content from *apps*. DP has currently the most attention. Since we have many *api* folders, you have to spell out *apps* completely for it to be unique - small productivity gain from using DP instead.

### Subfolders

* Move the *requirements* and *tutorial* folders "as is" and keep their naming in the new location.
* Move in *getting-started* and add *apps/activate/helper-application.md* to it.
* Create a new folder called *overview* or *terminology* in DP and place all concepts from both sources there.
* Move checklists and *apps/tenant-status/status-page.md* to *reference*.
* Move the 3 Watchcom pages + get/revoke consent to *security*.
* Move under but not including *apps/publish* to *app-store*.
* Move remaining how-tos scattered in *apps* to *howto*.
* Merge the index.yml and toc.yml and place *apps/best-practices.md* at top level
* Images and includes follow their parent Markdown files.

### Skeleton

* developer-portal
  * app-store
  * create-app
  * getting-started
  * howto
  * reference
  * requirements
  * security
  * terminology (or overview)
  * tutorials

**Comment by digitaldiina** [comment]
[toc-idea.md](https://github.com/SuperOfficeDocs/superoffice-docs/files/11396438/toc-idea.md)

Also discussed this today's meeting.
