### ISSUE TITLE
Missing items (pictures, text. etc)

### ISSUE THREAD

**Issue by pavlas77** [SuperOfficeDocs/superoffice-docs#55]
- [x] http://localhost:8080/docs/video-meeting/connect-provider.html - missing pictures
- [x] http://localhost:8080/docs/video-meeting/disconnect-provider.html - missing pictures
- [x] http://localhost:8080/docs/identity-management/superid/howto/register-idp.html - missing picture almost at the end of the text, in the Note section
- [x] http://localhost:8080/docs/documents/configure-cloud-document-handling.html - different text, pictures. I think the EPI document was updated after it has been migrated
- [x] http://localhost:8080/docs/mobile/superoffice-mobile/security.html - misisng some text in Local storage and differs from the original on a few places, FAQs at the bottom of the page
- [x] http://localhost:8080/docs/email/mailgun/reasons-to-customize.html - text is different than the original text, starting from Feedback from customers that leads to the need for customization is related mainly to these issues. It is on other page?

**Comment by digitaldiina** [comment]
re mobile security: no missing text in *local storage* the 2 links are in the text rather than raw URLs. FAQ is in its own file in the same folder (faq.md), visit http://localhost:8080/mobile/superoffice-mobile/faq.html

re mailgun: some of the content is in overview.md, some in security.md

re cloud documents: I updated the procedure. Hard to determine what has been changed in markdown due to edits vs. what was edited in EPI. We warned to keep markdown in sync with EPI after migration. Not going to re-do the migration. Please revise in markdown if necessary.

**Comment by pavlas77** [comment]
All done
