### ISSUE TITLE
Docs Search: Search result shows metadata title, not page title on page or table of content

### ISSUE THREAD

**Issue by kirstiaa** [SuperOfficeDocs/superoffice-docs#573]
Searching for a page title or the table of content title will give the meta data title of the page in the search result.
It feels a little confusing to not see the same naming when you search, in the search result and clicking one search line.

![Image](https://user-images.githubusercontent.com/102585577/209930737-d44dc24f-658a-489b-87d4-6aadf6e7ba35.png)

**Comment by SuperOfficeDevNet** [comment]
@kirstiaa, is this a request to change the metadata title and description properties to match the H1 title, or a request to change the H1 title to match the metadata title and description?

Since Find is now a screen, and no longer a dialog, the latter seems most appropriate. Is that what you had in mind?

If so, the fastest way to update this is to [edit the page submit a PR](https://docs.superoffice.com/en/contribute/how-to-edit-an-article-in-browser.html).

**Comment by Chrihagb** [comment]
Is this a request to change the metadata title and description properties to match the H1 title =yes

or a request to change the H1 title to match the metadata title and description? = No

But with H1 we mean this
![IMG_8525](https://user-images.githubusercontent.com/102592266/210217114-778642c2-e1df-44c1-8c10-c665c9f081ba.jpeg)
![IMG_8524](https://user-images.githubusercontent.com/102592266/210217137-d85e1fc9-dcec-4462-a4f7-ef45e600a2ad.jpeg)

**Comment by digitaldiina** [comment]
Aligning metadata and content is up to the person creating or updating a page, and a continuous effort.

It is not as simple as a bulk update, because sometimes the H1 is preferred, and in other cases the metadata title. Manually inspecting and updating 6000+ pages is more than a week's work... Even if we invested that time, there's no guarantee they will stay in sync.

For specific changes that cannot wait, edit the page and submit a PR.
